### PR TITLE
Add LowerBound and UpperBound options

### PR DESCRIPTION
**Pull request by carlosms**
This PR adds a couple of options to set the `min` and `max` values of the Y axis.
I needed them for a personal project and figured it might be useful to other people.

Update: options name updated to `LowerBound` and `UpperBound`

### CODE REVIEW

**Comment by jesseduffield** [comment]
I've been using this fork myself recently and can attest to its robustness. Let's get this baby merged!

**Comment by guptarohit** [comment]
Hi, @carlosms thanks for the PR :octocat: :heart:

These options are definitely needed, here I'm little skeptical about the name of the options. They actually mean `MinLower`, `MinUpper`; if possible, can we think of name other than `Min` & `Max`.

:wave: @jesseduffield would like to have your views on this.

Naming is hard! [Jeff Atwood's tweet](https://twitter.com/codinghorror/status/506010907021828096) :smile:

**Comment by jesseduffield** [comment]
@guptarohit Maybe LowerBound and UpperBound:

image

Although technically that's referring to data points on the graph.. damn.

This is tricky because as the end-user, the names which are most intuitive are coincidentally names that don't map well onto the actual terminology.

What about WindowMax and WindowMin?

**Comment by guptarohit** [comment]
@jesseduffield if I understand correctly these options ensure the minimum lower bound of the graph (therefore MinLower) & maximum upper bound of the graph(therefore MaxUpper),
as [L64](https://github.com/guptarohit/asciigraph/blob/22e3e1b9e3cd5ab4f79619cd65987f426d2d3dc4/options.go#L64)
> It will be ignored if the series contains a bigger value.

Whereas, `MaxUpper` or `Max` appear like it sets the max possible point on the graph. Please correct me if I'm wrong.

**Comment by jesseduffield** [comment]
@guptarohit I'm not quite sure what you mean. Do you want to use MinLower and MaxUpper or MinLower and MinUpper?

These comments don't seem to be cohesive:

> They actually mean MinLower, MinUpper
> maximum upper bound of the graph(therefore MaxUpper)
> MaxUpper or Max appear like it would set the max possible point on the graph.

At any rate, I'm find with MinLower and MaxUpper

**Comment by guptarohit** [comment]
hi @jesseduffield, I actually meant MinLower and MinUpper (edited my comment now, please check)

**Comment by jesseduffield** [comment]
@guptarohit I am still a little confused. Lets say that we're using this PR's terminology, and I set Min to 0 and Max to 10, but then my data set ranges from -10 to 20. The lowest value on the graph will be 0 and the highest value will be 10. I'm not sure why the Max would be better named MinUpper in that case

**Comment by guptarohit** [comment]
@jesseduffield I'm afraid it won't be like that as per this PR, please check the test case [ #16](https://github.com/guptarohit/asciigraph/blob/22e3e1b9e3cd5ab4f79619cd65987f426d2d3dc4/asciigraph_test.go#L211) or check the O/P by following example:

```go
data := []float64{-2, 1, 11, 2, -10, 5, 7, 11, -9, -4, -1, 5, 13, -2}
asciigraph.Plot(data, asciigraph.Min(0), asciigraph.Max(10))
```
```bash
  15.00 ┤       ╭╮     
  14.00 ┤       ││     
  13.00 ┤       ││  ╭╮ 
  12.00 ┤       ││  ││ 
  11.00 ┤ ╭╮   ╭╯│  ││ 
  10.00 ┤ ││   │ │  ││ 
   9.00 ┤ ││   │ │  ││ 
   8.00 ┤ ││   │ │  ││ 
   7.00 ┤ ││  ╭╯ │  ││ 
   6.00 ┤ ││  │  │  ││ 
   5.00 ┼ ││ ╭╯  │ ╭╯│ 
   4.00 ┤ ││ │   │ │ │ 
   3.00 ┤ ││ │   │ │ │ 
   2.00 ┤ │╰╮│   │ │ │ 
   1.00 ┤╭╯ ││   │ │ │ 
   0.00 ┤│  ││   │ │ │ 
  -1.00 ┤│  ││   │╭╯ │ 
  -2.00 ┼╯  ││   ││  ╰ 
  -3.00 ┤   ││   ││    
  -4.00 ┤   ││   ││    
  -5.00 ┤   ││   ││    
  -6.00 ┤   ││   ││    
  -7.00 ┤   ││   ││    
  -8.00 ┤   ││   ││    
  -9.00 ┤   ││   ╰╯    
 -10.00 ┤   ╰╯         

```

**Comment by jesseduffield** [comment]
That's strange, I'm not really sure whether Min or Max are having any effect at all there. I would have expected it to have a max y-axis value of 10, and a min of 0. @carlosms is the above example an expected output?

**Comment by medzernik** [comment]
Any progress on this?

**Comment by guptarohit** [comment]
Updated options names to `LowerBound` and `UpperBound`. This PR also resolves #26

**Pull request merged**
